# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fantasy_gestionale
spring.datasource.username=postgres
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# App
spring.application.name=fantasy-gestionale
server.port=8080

# JWT (lo usiamo dopo)
jwt.secret=fantasy-gestionale-chiave-segreta-32chars
jwt.expiration=86400000